filter:
    paths:
        - 'core/src/*'
    excluded_paths:
        - 'dist/*'
        - 'ext/*'
        - 'jdrivers/*'
        - 'core/src/data/*'
        - 'core/src/core/classes/dibi.compact.php'
        - 'core/src/core/classes/http_class/*'
        - 'core/src/core/classes/pclzip.lib.php'
        - 'core/src/core/classes/sabredav/lib/*'
        - 'core/src/core/classes/sabredav/vendor/*'
        - 'core/src/plugins/access.dropbox/dropbox-php/*'
        - 'core/src/plugins/access.hpcloud/HPCloud_Patch/*'
        - 'core/src/plugins/access.s3/aS3StreamWrapper/lib/*'
        - 'core/src/plugins/access.sftp_psl/phpseclib/*'
        - 'core/src/plugins/access.smb/smb.php'
        - 'core/src/plugins/auth.cas/CAS/*'
        - 'core/src/plugins/auth.radius/class.radiusAuthDriver.php'
        - 'core/src/plugins/core.mq/vendor/*'
        - 'core/src/plugins/editor.ckeditor/ckeditor/*'
        - 'core/src/plugins/editor.diaporama/PThumb.lib.php'
        - 'core/src/plugins/editor.etherpad/etherpad-client/*'
        - 'core/src/plugins/index.lucene/Zend/*'
        - 'core/src/plugins/meta.svn/svn_executor.inc.php'
        - 'core/src/plugins/meta.svn/svn_lib.inc.php'
tools:
    php_cs_fixer:
        filter:
            paths:
                - 'core/src/*'
            excluded_paths:
                - 'dist/*'
                - 'ext/*'
                - 'jdrivers/*'
                - 'core/src/data/*'
                - 'core/src/core/classes/dibi.compact.php'
                - 'core/src/core/classes/http_class/*'
                - 'core/src/core/classes/pclzip.lib.php'
                - 'core/src/core/classes/sabredav/lib/*'
                - 'core/src/core/classes/sabredav/vendor/*'
                - 'core/src/plugins/access.dropbox/dropbox-php/*'
                - 'core/src/plugins/access.hpcloud/HPCloud_Patch/*'
                - 'core/src/plugins/access.s3/aS3StreamWrapper/lib/*'
                - 'core/src/plugins/access.sftp_psl/phpseclib/*'
                - 'core/src/plugins/access.smb/smb.php'
                - 'core/src/plugins/auth.cas/CAS/*'
                - 'core/src/plugins/auth.radius/class.radiusAuthDriver.php'
                - 'core/src/plugins/core.mq/vendor/*'
                - 'core/src/plugins/editor.ckeditor/ckeditor/*'
                - 'core/src/plugins/editor.diaporama/PThumb.lib.php'
                - 'core/src/plugins/editor.etherpad/etherpad-client/*'
                - 'core/src/plugins/index.lucene/Zend/*'
                - 'core/src/plugins/meta.svn/svn_executor.inc.php'
                - 'core/src/plugins/meta.svn/svn_lib.inc.php'
        config:
            level: custom
            fixers: { indentation: true, linefeed: true, trailing_spaces: true, unused_use: true, visibility: true, short_tag: true, braces: true, php_closing_tag: true, controls_spaces: true, eof_ending: true }
    php_hhvm:
        filter:
            paths:
                - 'core/src/*'
            excluded_paths:
                - 'dist/*'
                - 'ext/*'
                - 'jdrivers/*'
                - 'core/src/data/*'
                - 'core/src/core/classes/dibi.compact.php'
                - 'core/src/core/classes/http_class/*'
                - 'core/src/core/classes/pclzip.lib.php'
                - 'core/src/core/classes/sabredav/lib/*'
                - 'core/src/core/classes/sabredav/vendor/*'
                - 'core/src/plugins/access.dropbox/dropbox-php/*'
                - 'core/src/plugins/access.hpcloud/HPCloud_Patch/*'
                - 'core/src/plugins/access.s3/aS3StreamWrapper/lib/*'
                - 'core/src/plugins/access.sftp_psl/phpseclib/*'
                - 'core/src/plugins/access.smb/smb.php'
                - 'core/src/plugins/auth.cas/CAS/*'
                - 'core/src/plugins/auth.radius/class.radiusAuthDriver.php'
                - 'core/src/plugins/core.mq/vendor/*'
                - 'core/src/plugins/editor.ckeditor/ckeditor/*'
                - 'core/src/plugins/editor.diaporama/PThumb.lib.php'
                - 'core/src/plugins/editor.etherpad/etherpad-client/*'
                - 'core/src/plugins/index.lucene/Zend/*'
                - 'core/src/plugins/meta.svn/svn_executor.inc.php'
                - 'core/src/plugins/meta.svn/svn_lib.inc.php'
        config:
            bad_php_include_file: true
            php_include_file_not_found: true
            use_undeclared_global_variable: true
            unknown_trait: true
    sensiolabs_security_checker: true
    php_loc:
        excluded_dirs:
            - 'dist'
            - 'ext'
            - 'jdrivers'
            - 'core/src/data'
            - 'core/src/core/classes/http_class'
            - 'core/src/core/classes/sabredav/lib'
            - 'core/src/core/classes/sabredav/vendor'
            - 'core/src/plugins/access.dropbox/dropbox-php'
            - 'core/src/plugins/access.hpcloud/HPCloud_Patch'
            - 'core/src/plugins/access.s3/aS3StreamWrapper/lib'
            - 'core/src/plugins/access.sftp_psl/phpseclib'
            - 'core/src/plugins/auth.cas/CAS'
            - 'core/src/plugins/core.mq/vendor'
            - 'core/src/plugins/editor.ckeditor/ckeditor'
            - 'core/src/plugins/editor.etherpad/etherpad-client'
            - 'core/src/plugins/index.lucene/Zend'
    php_pdepend:
        excluded_dirs:
            - 'dist'
            - 'ext'
            - 'jdrivers'
            - 'core/src/data'
            - 'core/src/core/classes/http_class'
            - 'core/src/core/classes/sabredav/lib'
            - 'core/src/core/classes/sabredav/vendor'
            - 'core/src/plugins/access.dropbox/dropbox-php'
            - 'core/src/plugins/access.hpcloud/HPCloud_Patch'
            - 'core/src/plugins/access.s3/aS3StreamWrapper/lib'
            - 'core/src/plugins/access.sftp_psl/phpseclib'
            - 'core/src/plugins/auth.cas/CAS'
            - 'core/src/plugins/core.mq/vendor'
            - 'core/src/plugins/editor.ckeditor/ckeditor'
            - 'core/src/plugins/editor.etherpad/etherpad-client'
            - 'core/src/plugins/index.lucene/Zend'
    php_analyzer: true
